allowBuilds:
  '@parcel/watcher': true
  react-particles: true
  sharp: true
  tsparticles-engine: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - react-particles
  - sharp
  - tsparticles-engine
  - unrs-resolver
